# Update versions with `pre-commit autoupdate`.
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-ast
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials]
    -   id: detect-private-key
    -   id: check-merge-conflict
    -   id: check-added-large-files
        args: ['--maxkb=1000']
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
-   repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
    - id: isort
      name: isort
-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    -   id: black
-   repo: https://github.com/flakehell/flakehell
    rev: v.0.8.0
    hooks:
    - id: flakehell
      additional_dependencies:
          - flake8==3.9.0 # Avoids flakehell bug: https://github.com/flakehell/flakehell/issues/10
          - flake8-bugbear
          - flake8-builtins
          - pep8-naming
-   repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
    - id: nbstripout
-   repo: https://github.com/AleksaC/hadolint-py
    rev: v1.19.0
    hooks:
      - id: hadolint
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        types: [markdown]
